dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install -r requirements.txt

script:
    - pytest --cov=src

after_success:
    - bash <(curl -s https://codecov.io/bash)
